server:
  port: 5057

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:5054/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bilal20208/config-server
          clone-on-start: true